### ISSUE TITLE
Some questions when I try to reproduce

### ISSUE THREAD

**Issue by LinXueyuanStdio** [vinhsuhi/EMGCN#1]
Hello, thanks for sharing the code! EMGCN is extremely efficient and of high quality. I love it!
However, when I try to reproduce, there are several questions that cause confusion. All questions are listed below.

1. num_each_refine is undefined. It looks like a hyper parameter. However, I can't find any sentences mention it in the paper. What number should be set as default in order to reproduce the result in paper?
2. Due to machine limitation, it throws "CUDA out of memory" exception when running code below:
    ```python
    A_hat_new = (alpha_colum * (A_hat.mul(alpha_colum)).t()).t()
    ```
    To continue, I fix it by adding lines:
    ```python3
    if hasattr(torch.cuda, 'empty_cache'):
        torch.cuda.empty_cache()
    ```
    It works, but the result is not ok.
    ```
    left to right...
    Hit_1: 0.7147
    Hit_10: 0.8662
    Hit_50: 0.9326
    Hit_100: 0.9501
    MAP: 0.7678
    AUC: 0.9944
    Full_time: 2887.4527
    right to left...
    Hit_1: 0.6726
    Hit_10: 0.8450
    Hit_50: 0.9247
    Hit_100: 0.9489
    MAP: 0.7329
    AUC: 0.9964
    Full_time: 2920.7518
   ```
   The hit@1 is too low comparing to 0.86 in the paper. What should I do to gain 0.86? 
   My parameters are attached below:
   ```
    Namespace(
       act='tanh',
       algorithm='EMGCN',
       dataset_name='zh_en',
       groundtruth ='data/networkx/zh_enDI/dictionaries/groundtruth', 
       source_dataset='data/networkx/zh_enDI/zh/graphsage/',
       target_dataset='data/networkx/zh_enDI/en/graphsage',
       cuda=True,
       log=False,
       sparse=True,
       seed=123, 
       att=0.5,
       attval=0.5,
       direct_adj=False,
       emb_epochs=200,
       embedding_dim=100, 
       lr=0.01,
       num_GCN_blocks=2,
       num_each_refine=10,
       refinement_epochs=10,
       point=1.1,
       rel=1,
       threshold_refine=0.8)
   ```
Looking forward to your reply.

**Comment by vinhsuhi** [comment]
Thanks for your question! And sorry for my late response!

I have already double-checked my code, and there is a bug when I cleaned the code and pushed it to github. 
The bugs related to the attribute similarity matrix, and I have already fixed it!

Moreover, for zh_en dataset, I recommend you try to use att=0.25 and attval=0.25. You can lower the number of refinement epochs to achieve a faster training. 

Please pull the code and notify me if you have any problems!

**Comment by Remorax** [comment]
Hi @vinhsuhi ,

The current version of the code throws an error on running in the default setting. More specifically, I get this error:

`File "/data/Vivek/IBM/EMGCN-full/EMGCN/algorithms/EMGCN/EMGCN.py", line 255, in train_embedding                           att_simi_matrix = self.att_simi_matrix + self.value_simi_matrix
AttributeError: 'EMGCN' object has no attribute 'att_simi_matrix'`

The error occurs in this [line](https://github.com/vinhsuhi/EMGCN/blob/master/algorithms/EMGCN/EMGCN.py#L255https://github.com/vinhsuhi/EMGCN/blob/master/algorithms/EMGCN/EMGCN.py#L255) as `self.att_simi_matrix`  is not defined.

Perhaps your removing [this line](https://github.com/vinhsuhi/EMGCN/commit/ba77e8818e6265f6f17db6154161d22df52c2467#diff-e7c7af24b27e0dc7e81bf70ef08ea6fb47a1de64db9f42f205c631a805c7f796L250) in your last commit caused this? 

I request you to fix this at the earliest as we wish to include your excellent work as a baseline in our upcoming paper.

**Comment by vinhsuhi** [comment]
Hi @Remorax,
I have just fixed your mentioned bug.

**Comment by Remorax** [comment]
Awesome, thank you so much! :)

**Comment by 1453287898** [comment]
Can I ask you the source dataset? The link which author provided is lose.Thank you so much
